In [47]:
#[Course Name ::: Machine Learning A-Z ]
#[Part 1 - Data Pre-processing]
#[Downloading the dataset .... www.superdatascience.com/machine-learning]

#[First Step - Importing the libraries]
#[3 essential libraries --- Numpy,matplotlib,pandas]
import numpy as np;
import matplotlib.pyplot as plt;
import pandas as pd;
print('All the above libraries are imported')

All the above libraries are imported


In [48]:
# Importing the dataset . The file is under the same directory as the conda root.
dataset = pd.read_csv('Datasets//Part 1 - Data Preprocessing//Section 2 -------------------- Part 1 - Data Preprocessing --------------------//Data.csv');

In [49]:
#Now we need to separate the dependant and the independant variables.

x= dataset.iloc[:,:-1].values
y = dataset.iloc[:,3].values


In [50]:
# Now , we need to take care of missing data.

print("The missing data >>>",x[:,1:3])

# Most common idea is to replace it by the mean of the column.

from sklearn.preprocessing import Imputer

#we use the above library and take imputer class alone.
# missing_values --> what values am i replacing .. i need to replace the values that are NaN in my dataset
# strategy --> how am i imputing the missing values ... mean (default strategy)
# axis --> axis = 0 (along columns) axis = 1 (along rows)
imputer= Imputer(missing_values = 'NaN',strategy = 'mean',axis = 0)

#Now we need to fit this imputer object into our dataset.
# the missing values are in second and third column.Python has index from zero, but 
# while slicing the data the lower bound is included but the upper bound isn't. That is 
# why we have selected 1:3 and not 1:2 (this will select only the second column)
imputer=imputer.fit(x[:,1:3])

x[:,1:3] = imputer.transform(x[:,1:3])
print("The imputed dataset >>>",x[:,1:3])


The missing data >>> [[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 nan]
 [35.0 58000.0]
 [nan 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]
The imputed dataset >>> [[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 63777.77777777778]
 [35.0 58000.0]
 [38.77777777777778 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]


In [51]:
# Encode categorical data 
# In this dataset , the country data has 3 categories (Spain,France and Germany) 
# and the purchased has 2 categories(yes and no)

from sklearn.preprocessing import LabelEncoder , OneHotEncoder
labelEncoder_x = LabelEncoder()
print("This is how the encoded values of the country column look like >>>",labelEncoder_x.fit_transform(x[:,0]))
x[:,0] = labelEncoder_x.fit_transform(x[:,0])

# The problem that arises by encoding the categories is that, the machine learning algorithm thinks that 
# the countries with higher number carry higher value ..but that doesnt make any sense.
# Hence , we create dummy columns .. 

one_hot_x = OneHotEncoder(categorical_features = [0]);
x = one_hot_x.fit_transform(x).toarray()
print("The features now looks like >>>",x[:, 0:3])

# For the dependant variable , there is no need to perform one hot encoding (or create dummy columns ) 
# because the machine learning algorithm will know that it is a category and there is no order between them.

labelEncoder_y = LabelEncoder()
y = labelEncoder_x.fit_transform(y)

This is how the encoded values of the country column look like >>> [0 2 1 2 1 0 2 0 1 0]
The features now looks like >>> [[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]]


In [52]:
#[Next step is to split the dataset into train and test data.]
#[Reason --> When the ML algorithm learns something .. 
# we need to test the output against some data to verify its learning capabilities]
from sklearn.cross_validation import  train_test_split
x_train ,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)


In [53]:
# The next step is Feature scaling ..
# Most of the machine learning algorithms compute  euclidean distances between observations.
# if the observations are not scaled along in the same range then the observation which has a higher number will dominate 
# other observations and the model will be skewed.
# 2 types --> Standardisation and normalization
# Standardisation --> x(i)-mean(x)/sd(x)
# Normalization --> x(i)-min(x)/max(x)-min(x)

from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)
print ("The scaled train data <<<",x_train)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)

# Note : Some of the machine learning algorithms do take care of Feature scaling by itself.
# For this course , a pre-processing template is created wherein only the loading of the dataset and the splitting 
# the data into a train and test is present. The data used in the course is pretty much clean and hence handling missing 
# data is not needed. The feature scaling may be needed for some algorithms.

The scaled train data <<< [[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]


/home/ubuntu/anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/ubuntu/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:583: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/home/ubuntu/anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/ubuntu/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:646: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError